### PR TITLE
Changed maintainer and added token to vignettes

### PR DESCRIPTION
**Pull request by mandawilson**
- Changed maintainer
- Added token to vignettes
- Added `.travis.yml` to `.Rbuildignore` so that we do not get the following when we run `R CMD check cgdsr_1.3.0.tar.gz`
```checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .travis.yml
```

### CODE REVIEW

**Review by cannin — CHANGES_REQUESTED** [review]
@mandawilson how does a user get a token? Does this mean that a token is not necessary for the public instance? If so, that would be nice to state.

**Review by sheridancbio — APPROVED** [review]
looks good

**Comment by sheridancbio** [comment]
The optionality of the token might be emphasized in the docs by changing:
A token option can be set for the CGDS connection object.
to something like:
[Optional] A data access token can be optionally attached to a CGDS connection objects when they are created.

Also I would keep any details of how to create a token to a minimum (because the process may change over time). But I might add a line like "Data access tokens (when this feature is enabled) can be created through the cbioportal website"

**Review by ao508 — APPROVED** [review]

**Comment by mandawilson** [comment]
@cannin As @sheridancbio said we want to keep details of how to get a token to a minimum, but I added some text explaining that you would get it from the portal website.  The portal website will soon have documentation about exactly how to get a token.  I also now explicitly say that the public portal does not require a token.

**Review by cannin — APPROVED** [review]

**Pull request merged**
